/* ============================================================
   Byte-parity proof for the ported ETH→KOIN engine.

   tests/fixtures/eth-vectors.json was generated by running Koinos Node
   Desktop's OWN modules (the battle-tested implementation this engine is
   ported from) with fixed inputs. Every calldata builder here must
   reproduce those vectors byte-for-byte — same to, same data, same value —
   so the port provably moves money exactly like the original.

   Run: node tests/eth-parity.test.js
   ============================================================ */
"use strict";
const assert = require("assert");
const path = require("path");
const { ethers } = require("ethers");

const V = require(path.join(__dirname, "fixtures", "eth-vectors.json"));
const swap = require("../tools/eth/eth-swap-exec.js");
const { buildTransferTokensTx } = require("../tools/eth/eth-bridge-token.js");
const { recordToRedeemArgs } = require("../tools/eth/koinos-bridge.js");
const { weiToVethSats, computeQuorum } = require("../tools/eth/bridge.js");
const { compareRoutes } = require("../tools/eth/fund-routes.js");
const { BRIDGE_ABI } = require("../tools/eth/eth-bridge.js");
const RC = require("../tools/eth/route-constants.js");

const RECIP = "0x1111111111111111111111111111111111111111";
const KOINOS_RECIP = "1FgL97myhTgvVLRJP92e2h9avoxZuuySqL";

const eq = (name, ours, ref) => {
  assert.strictEqual(String(ours.to), String(ref.to), name + ": to");
  assert.strictEqual(String(ours.data), String(ref.data), name + ": calldata");
  assert.strictEqual(String(ours.value ?? "0"), String(ref.value ?? "0"), name + ": value");
  console.log("✓ " + name + " byte-identical (" + ((ref.data.length - 2) / 2) + " bytes)");
};

eq("ETH→USDT swap (v3 exactInputSingle)",
  swap.buildEthToUsdtTx({ recipient: RECIP, amountWei: "12345678900000000", fee: 500, minUsdtOut: "41000000" }),
  V.ethToUsdt);

eq("ERC-20 approve (USDT→Permit2, max)",
  swap.buildApproveTx(RC.USDT, RC.PERMIT2, swap.MAX_UINT256),
  V.approve);

eq("Permit2 approve (USDT→UniversalRouter)",
  swap.buildPermit2ApproveTx({ token: RC.USDT, spender: RC.UNIVERSAL_ROUTER, amount: "41000000", expiration: 1767225600 }),
  V.permit2);

eq("USDT→vKOIN swap (v4 UniversalRouter)",
  swap.buildUsdtToVkoinTx({ usdtAmount: "41000000", minVkoinOut: "52000000000", deadline: 1767225600 }),
  V.usdtToVkoin);

eq("vKOIN→bridge transferTokens",
  buildTransferTokensTx({ token: RC.VKOIN, amountSats: "52000000000", koinosRecipient: KOINOS_RECIP, network: "mainnet" }),
  V.transferTokens);

eq("ETH deposit wrapAndTransferETH", {
  to: "0x2F2f36A88DD5ff8d53Ba2505b2DbC0C153d910Ab",
  data: new ethers.Interface(BRIDGE_ABI).encodeFunctionData("wrapAndTransferETH", [0, "", KOINOS_RECIP, "", 1]),
  value: "12345678900000000",
}, V.wrapAndTransfer);

/* Pure helpers agree with the original */
assert.deepStrictEqual(
  JSON.parse(JSON.stringify(weiToVethSats("12345678901234567890"))), V.weiToVeth);
assert.strictEqual(computeQuorum(3), V.quorum.three);
assert.strictEqual(computeQuorum(7), V.quorum.seven);
assert.deepStrictEqual(
  recordToRedeemArgs({
    id: "0xabc123", recipient: KOINOS_RECIP, koinosToken: "19GYjDBVXU7keLbYvMLazsGQn3GTWHjHkK",
    amount: "52000000000", payment: null, metadata: "", relayer: "",
    signatures: ["sigA", "sigB"], expiration: "1767225600000",
  }), V.redeemArgs);
assert.deepStrictEqual(
  compareRoutes([
    { id: "B", koinOut: "100000000" },
    { id: "C", koinOut: "250000000" },
    { id: "X", koinOut: null, error: "quote failed" },
  ]), V.compare);
console.log("✓ pure helpers (wei→vETH, quorum, redeem args, route compare) identical");

/* The NEW USDC leg: same interface, same shape, USDC in — self-consistent with
   the reference builder pattern (assert against a direct Interface encode). */
const usdc = swap.buildUsdcToUsdtTx({ recipient: RECIP, usdcAmount: "50000000", fee: 100, minUsdtOut: "49900000" });
const expect = new ethers.Interface([
  "function exactInputSingle((address tokenIn,address tokenOut,uint24 fee,address recipient,uint256 amountIn,uint256 amountOutMinimum,uint160 sqrtPriceLimitX96)) payable returns (uint256)",
]).encodeFunctionData("exactInputSingle", [
  { tokenIn: RC.USDC, tokenOut: RC.USDT, fee: 100, recipient: RECIP, amountIn: 50000000n, amountOutMinimum: 49900000n, sqrtPriceLimitX96: 0 },
]);
assert.strictEqual(usdc.to, RC.V3_SWAP_ROUTER);
assert.strictEqual(usdc.data, expect);
assert.strictEqual(String(usdc.value), "0");
assert.strictEqual(RC.USDC, "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48");
console.log("✓ USDC→USDT builder: v3 exactInputSingle, USDC canonical address, value 0");

console.log("\nALL ETH-ENGINE PARITY CHECKS PASSED");
